### ISSUE TITLE
General pending issues

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Solarpunk-DAO#1]
**@Riki0923** 
- [x] Feedback on [Governance contract issues](https://github.com/zenbitETH/Solarpunk-DAO/issues/3)
- [x] Governance contract for Solarpunk DAO

**@HabacucMX** 
- [x] [Project draft](https://docs.google.com/document/d/1s8Tr-G7SScIkg0_0DZiNnL5OGeYNdDBsWVytEfZ5ii0/edit?usp=sharing)
- [x] Documentation for Solarpunks DAO hack
- [x] [Flowchart for interactions between Punk Cities and Solarpunks DAO
](https://www.figma.com/file/FX1CchcQ3r8YNm95Em3REG/Solarpunk-DAO?node-id=0%3A1)
- [x] Clone [Solarpunks repo](https://github.com/rtang03/solarpunks) for DAO governance #2 
- [x] Watch and enlist functions from governance workshop

**React App/Next.js Dapp (Team)**  
_[User login]_
- [x] Connect to mumbai
- [x] Connect to lens
- [x] Create profile
- [x] Follow profile
- [x] Fetch users' punk cities NFTs  

_[Teamback]_
- [x] Review of the flowchart on a voice call

_[DAO governance]_
- [x] Governance  #6 
- [x] Create proposal (as lens post) #6 
- [x] Proposal Detail
- [x] Vote for proposals (as follow on lens?)
- [x] Voting power (deposit to treasury) Not used, it change for join button
- [x] Past proposals (hardwired on dashboard for now)
- [x] Marketplace? (look use cases) (OMITED)

**DAO Hack (Team)**
- [x] Fill project submission on the dashboard
- [x] Backgrounds for video #5 
- [x] 4 Minutes video
- [x] Logo
- [x] 3 snapshots
- [x] 🏁 Submit project and choose judging time🏁
